### ISSUE TITLE
Importing JSON annotations from previous Advene session isn't working 

### ISSUE THREAD

**Issue by a-darcher** [oaubert/advene#65]
Hi Advene team, 

really like Advene and using it has improved my annotation workflow a ton! 

I'm running into an issue on the current version while trying to import JSON files generated in a previous Advene session. 
When I import the JSON file using the Importer tool, setting the filter to WebAnnotation importer, it cannot successfully import the file and only adds an empty annotation. Is the WebAnnotation filter not the correct one for JSON files, or is there another issue? 

Here is a screenshot showing the pop-up message post-importing:
![Screenshot from 2021-03-22 12-06-29](https://user-images.githubusercontent.com/37139973/111993836-603c3800-8b17-11eb-8500-56db1ee84015.png)

**Comment by oaubert** [comment]
Thanks for the report, there were some errors in the webannotation import filter (as well as duplicated WebAnnotation export filters - the old template-based on overriding the newer python-based one). I have just fixed these.

**Comment by a-darcher** [comment]
I'm trying to re-install advene from the GH source in order to make use of your fixes, but I'm running into some issues with `make`-ing the executable (namely -- epydoc hasn't been updated for Python 3 and throws errors during the build). 

Is there any chance that you are planning to release a new debian binary with the updated changes? 
Conversely -- is there an obvious way of using advene from GH source that I'm missing? :) 

Thanks!

**Comment by oaubert** [comment]
A new release should occur soon, but I have some unfinished patches to integrate. If you want to run the git version from sources, you can uninstall the Debian package (so that there is no confusion between installed and dev modules) and simply run `./bin/advene` from the git tree.

**Comment by franzigrkn** [comment]
I am trying the same thing and as you suggested, I installed the current git version from source, but unfortunately I still cannot import the json file correctly. I get the same error message as shown above and there is just an empty annotation imported. Just for clarification: I work on Linux and installed all required packages in a Conda env, cloned the git repo and ran ./bin/advene -pdummy. Up to here, everything works fine, but the import fails. Do you have any idea what the reason might be?

I also wondered if there is way of converting the json to a format which can be accepted by advene?

Thanks already in advance!

**Comment by oaubert** [comment]
Were your json files exported as Flat JSON, or WebAnnotation?

**Comment by franzigrkn** [comment]
As far as I know it has been exported as Flat JSON.

**Comment by oaubert** [comment]
OK. Then you can update from the git tree, I added this morning a FlatJSON importer, which is able to re-import data exported using the FlatJSON export format.

**Comment by franzigrkn** [comment]
That worked! :) Thank you very much for your help, I appreciate it!
