### ISSUE TITLE
"Checker" does not open

### ISSUE THREAD

**Issue by johannakeil** [oaubert/advene#99]
I am reaching out regarding an issue I encountered while trying to use the "Checker" tool. When I attempt to open it, I receive the following error message:
```
advene.core.controller - ERROR - General exception <class 'OverflowError'> 18446744073709 not in range -2147483648 to 2147483647 <traceback object at 0x000001c82534b640>
NoneType: None
```
I have ensured that I am using the latest version of the software.
Could you please assist me in resolving this issue? Any guidance or troubleshooting steps you could provide would be greatly appreciated.

Thank you for your assistance.

Best regards,
Johanna

**Comment by oaubert** [comment]
I would need more complete log information. It is saved in the advene.log file. To find it, open Help menu/Open logfile folder, then select the advene.log file and send it to support@advene.org
If your annotation file does not contain confidential information, you can send it too, because the error looks like it is data dependent.

**Comment by AdaTsche** [comment]
Same Problem here. OverflowError occurs when I'm trying to open the Checker or the table view of an annotation type with many annotations (800). I'll also send logfile and advene package to the support email.
Greetings & many thanks!

**Comment by johannakeil** [comment]
I sent my log file and my advene package - are there any news on how I can correct my annotations?
Help is very much appreciated.
Greetings and many thanks! :)

**Comment by oaubert** [comment]
It seems I have an issue with mails to advene.org which prevented reception. I am fixing it, but in the meantime could  you resend the mail to advene@olivieraubert.net which is ok.

**Comment by oaubert** [comment]
The issue is due to wrong timestamps in some annotations (the last 3 Shot annotations, with a timestamp of 18446744073709, which in ms corresponds to 585 years). I have fixed the checker view anyway so that it does not crash with such values, but before the production of a new installer, you can delete these annotations: with the package finder component, select schema / Montage / Shot, then delete the annotations 772, 773 and 774 (with a timestamp displayed as 23:34:33.709)

**Comment by johannakeil** [comment]
Awesome, thanks!
I found and deleted the annotations with the wrong timestamps. The Annotations of _montage / shot_ are now able to display as Annotation Table View again.
Unfortunately, a Checker Error still occurs, the logfile says:
```
 - advene.core.controller - ERROR - General exception <class 'AttributeError'> 'gi.repository.Gtk' object has no attribute 'RESIZE_IMMEDIATE' <traceback object at 0x0000018fb3d8eb40>
NoneType: None
```

How can I find the object which seems to hinder the Checker from working?

Many thanks & greetings!

**Comment by johannakeil** [comment]
Thank you for updating the code! I replaced the two files, but the Checker gives me this ERROR message again:
`- advene.core.controller - ERROR - General exception <class 'OverflowError'> 18446744073709 not in range -2147483648 to 2147483647 <traceback object at 0x000001a0aa1f8040>
NoneType: None`
I have tried turning my PC off and on again - maybe I have to download all changed files of the past months since the Update? Is there a download of all new files?

Thanks a lot for your time!
All the best
Johanna

**Comment by oaubert** [comment]
The fix was only present in the `dev` branch, to test deployment. If you are running from source, I guess it is from the `master` branch, that I just updated now. You can retry to update the code. You can also try the windows installer that has been generated in the `dev` branch (see the installer download at the end of https://github.com/oaubert/advene/actions/runs/11499632551 )
